### ISSUE TITLE
[Feature request] Additional CDN URL support

### ISSUE THREAD

**Issue by Seia-Soto** [zhoukekestar/snowpack-plugin-import-map#6]
Since this package used Skypack CDN to make the URL of the remote packages automatically, I was needed to search every package on CDNJS to use CDNJS instead of Skypack. I think it would be nice if there is an option to set CDN URL manually.

# Summary

Giving user a function option to set CDN URL of packages.

# Example usage

If this implemented, it will look like below:

```JS
{
  ...,
  makeUrl: (pkgName, version...) => 'https://cdn/pkgName@version'
}
```

Thank you.

**Comment by zhoukekestar** [comment]
You can try this rollup plugin, https://github.com/zhoukekestar/rollup-plugin-import-to-url.
What i'm using now is rollup, which can give me more flexibility. 
It would be pleasure if you can create a PR to implement this feature

**Comment by Seia-Soto** [comment]
I wrote a PR #7 for this. I don't know if you like, so feedback freely.
